import Head from 'next/head';
import { useState } from 'react';
import { Dialog } from '@headlessui/react';
import { Bars3Icon, XMarkIcon } from '@heroicons/react/24/outline';
import Link from 'next/link';
import Footer from '@/components/Footer';
import Article from '@/components/Article';

const navigation = [
  { name: 'Inicio', href: '/' },
  { name: 'Servicios', href: '/#services' },
  { name: 'Clasificados', href: '/clasificados' },
];

const posts = [
  {
    id: 1,
    title: 'OFICINAS EN VENTA EDIFICIO ACOCENTRO 94 (CHICO)',
    href: '#',
    description: 'Telefono: 3174765642',
    imageUrl: 'c1c.jpg',
    date: 'Marzo 23, 2023',
    datetime: '2020-03-16',
    category: { title: 'Oficinas', href: '#' },
    author: {
      name: 'Yenny Muriel',
      role: 'Gerente General',
      href: '#',
      imageUrl: 'logo.png',
    },
    images: ['c1a.jpg', 'c1b.jpg', 'c1c.jpg', 'c1d.jpg', 'c1e.jpg', 'c1f.jpg'],
  },
  // {
  //   id: 2,
  //   title: 'VENTA DE APARTAMENTOS CEDRITOS',
  //   href: '#',
  //   description: 'Telefono: 3174765642',
  //   imageUrl: 'c2a.jpg',
  //   date: 'Marzo 23, 2023',
  //   datetime: '2020-03-10',
  //   category: { title: 'Apartamentos', href: '#' },
  //   author: {
  //     name: 'Yenny Muriel',
  //     role: 'Gerente General',
  //     href: '#',
  //     imageUrl: 'logo.png',
  //   },
  //   images: ['c2a.jpg', 'c2b.jpg', 'c2c.jpg', 'c2d.jpg', 'c2e.jpg', 'c2f.jpg', 'c2g.jpg'],
  // },
];

export default function Market() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);

  return (
    <>
      <Head>
        <title>ML Condominios | Clasificados</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main className="h-full overflow-y-auto">
        <header className="relative inset-x-0 top-0 z-10">
          <nav className="mx-auto flex max-w-7xl items-center justify-between p-2 lg:px-8" aria-label="Global">
            <div className="flex lg:hidden">
              <button type="button" className="-m-2.5 inline-flex items-center justify-center rounded-md p-2.5 text-gray-700" onClick={() => setMobileMenuOpen(true)}>
                <span className="sr-only">Open main menu</span>
                <Bars3Icon className="h-6 w-6" aria-hidden="true" />
              </button>
            </div>
            <img src="logo.png" alt="logo" className="h-20 w-auto" />
            <div className="hidden lg:flex lg:gap-x-12">
              {navigation.map((item) => (
                // Smooth scroll
                <Link key={item.name} href={item.href} className="-mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">
                  {item.name}
                </Link>
              ))}
            </div>
          </nav>
          <Dialog as="div" className="lg:hidden" open={mobileMenuOpen} onClose={setMobileMenuOpen}>
            <div className="fixed inset-0 z-50" />
            <Dialog.Panel className="fixed inset-y-0 right-0 z-50 w-full overflow-y-auto bg-white px-6 py-6 sm:max-w-sm sm:ring-1 sm:ring-gray-900/10">
              <div className="flex items-center justify-between">
                <a href="/" className="-m-1.5 p-1.5">
                  <span className="sr-only">Your Company</span>
                  <img className="h-8 w-auto" src="logo.png" alt="" />
                </a>
                <button type="button" className="-m-2.5 rounded-md p-2.5 text-gray-700" onClick={() => setMobileMenuOpen(false)}>
                  <span className="sr-only">Close menu</span>
                  <XMarkIcon className="h-6 w-6" aria-hidden="true" />
                </button>
              </div>
              <div className="mt-6 flow-root">
                <div className="-my-6 divide-y divide-gray-500/10">
                  <div className="space-y-2 py-6">
                    {navigation.map((item) => (
                      <Link key={item.name} href={item.href} className="-mx-3 block rounded-lg py-2 px-3 text-base font-semibold leading-7 text-gray-900 hover:bg-gray-50">
                        {item.name}
                      </Link>
                    ))}
                  </div>
                </div>
              </div>
            </Dialog.Panel>
          </Dialog>
        </header>
        <div className="bg-white py-24 sm:py-32">
          <div className="mx-auto max-w-7xl px-6 lg:px-8">
            <div className="mx-auto max-w-2xl text-center">
              <h2 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">Clasificados</h2>
              <p className="mt-2 text-lg leading-8 text-gray-600">Todo lo que buscas en un solo lugar.</p>
            </div>
            <div className="mx-auto mt-16 grid max-w-2xl grid-cols-1 gap-y-20 gap-x-8 lg:mx-0 lg:max-w-none lg:grid-cols-3">
              {posts.map((post) => (
                <Article key={post.id} post={post} />
              ))}
            </div>
          </div>
        </div>
        <Footer />
      </main>
    </>
  );
}
